wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/simclr_cont_loss_pos_included/single-epoch-resnet-cont.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1647402489
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 3
      - 13
      4: 3.8.12
      5: 0.12.9
      8:
      - 5
